name: turb
channels:
  - rusty1s
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autopep8=1.5.7=pyhd8ed1ab_0
  - beniget=0.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - cffi=1.14.6=py38ha65f79e_0
  - cftime=1.2.1=py38heb32a55_0
  - chardet=4.0.0=py38h578d9bd_1
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - curl=7.71.1=h8f29fe8_2
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask-core=2021.7.2=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - decorator=4.4.2=py_0
  - distro=1.5.0=pyh9f0ad1d_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - enum34=1.1.10=py38h32f6830_2
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fftw=3.3.8=nompi_hfc0cae8_1114
  - fluiddyn=0.3.3=py38h578d9bd_1
  - fluidfft=0.3.2=nompi_h8fcda2e_100
  - fluidsim=0.4.1=py38h1fd1430_1
  - fluidsim-core=0.4.1=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.7.0=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_3
  - gast=0.5.0=pyhd8ed1ab_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5netcdf=0.11.0=pyhd8ed1ab_0
  - h5py=3.3.0=nompi_py38h9915d05_100
  - harfbuzz=2.8.2=h83ec7ef_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - hydra=2.5=py38h497a2fe_0
  - icu=68.1=h58526e2_0
  - imagecodecs-lite=2019.12.3=py38h5c078b8_3
  - imageio=2.9.0=py_0
  - importlib-metadata=4.6.3=py38h578d9bd_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipython_genutils=0.2.0=py_1
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_core=4.7.1=py38h578d9bd_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.2=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=10_mkl
  - libcblas=3.9.0=10_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.71.1=h303737a_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=10_mkl
  - liblapacke=3.9.0=10_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.6.1=h2053bdc_4
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.2=py38hcdf9bf1_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.15.8=h780b84a_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h497a2fe_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h1abd341_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nbstripout=0.5.0=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - netcdf4=1.5.7=py38h0a24e14_0
  - nettle=3.6=he412f7d_0
  - networkx=2.6.2=pyhd8ed1ab_0
  - ninja=1.10.2=hff7bd54_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.1=py38h1abd341_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathlib=1.0.1=py38h578d9bd_4
  - pcre=8.45=h9c3ff4c_0
  - pip=21.2.2=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.2=py38hd0cf306_0
  - pycodestyle=2.7.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfftw=0.12.0=py38h8e28c27_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster=1.5.9=py38_torch_1.9.0_cu102
  - pytorch-geometric=1.7.2=py38_torch_1.9.0_cu102
  - pytorch-scatter=2.0.8=py38_torch_1.9.0_cu102
  - pytorch-sparse=0.6.11=py38_torch_1.9.0_cu102
  - pytorch-spline-conv=1.2.1=py38_torch_1.9.0_cu102
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h5c078b8_3
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd8ed1ab_0
  - scikit-image=0.18.2=py38h1abd341_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - setuptools-scm=6.0.1=pyh44b312d_0
  - setuptools_scm=6.0.1=hd8ed1ab_0
  - sip=4.19.25=py38h709712a_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboardx=2.2=pyhd8ed1ab_0
  - termcolor=1.1.0=py38h06a4308_1
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tifffile=2019.7.26.2=py38_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - transonic=0.4.10=py38h578d9bd_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xarray=0.19.0=pyhd8ed1ab_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==0.13.0
    - antlr4-python3-runtime==4.8
    - certifi==2021.5.30
    - charset-normalizer==2.0.4
    - dm-control==0.0.364896371
    - dm-env==1.5
    - dm-tree==0.1.6
    - dmc2gym==1.0.0
    - glfw==2.1.0
    - gym==0.18.3
    - hydra-core==0.11.3
    - idna==3.2
    - importlib-resources==5.2.2
    - labmaze==1.0.5
    - lxml==4.6.3
    - numpy==1.21.1
    - omegaconf==1.4.1
    - pillow==8.2.0
    - protobuf==3.17.3
    - pyglet==1.5.15
    - pyopengl==3.1.5
    - pyyaml==5.4.1
    - scipy==1.7.1
    - setuptools==57.4.0
prefix: /scratch/diegopc/virtualenvs/miniconda3/envs/turb
